name: Go

on:
  pull_request:
    branches:
    - main
  push:
    branches:
    - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go ${{ matrix.go-version }}
      uses: actions/setup-go@v5
      with:
        go-version: 1.23.0
    - name: Check out code into the Go module directory
      uses: actions/checkout@v4
    - name: Build and Lint
      run: |
         go build ./...
         go vet ./...
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: "Set up Go"
        uses: actions/setup-go@v5
        with:
          go-version: 1.23.0
      - name: Check out code
        uses: actions/checkout@v4
      - name: Lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest
          args: --config ./.golangci.yml --timeout=2m
  test:
    name: Test ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
    - name: Set up Go ${{ matrix.go-version }} on ${{ matrix.os }}
      uses: actions/setup-go@v5
      with:
        go-version: 1.23.0
    - name: Check out code into the Go module directory
      uses: actions/checkout@v4
    - name: Test on ${{ matrix.os }}
      run: |
         go test ./...
  vulncheck:
    name: Vulncheck
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go ${{ matrix.go-version }}
      uses: actions/setup-go@v5
      with:
        go-version: 1.23.0
    - name: Check out code into the Go module directory
      uses: actions/checkout@v4
    - name: Get govulncheck
      run: go install golang.org/x/vuln/cmd/govulncheck@latest
      shell: bash
    - name: Run govulncheck
      run: govulncheck ./...
      shell: bash
